[package]

name = "membuf"
version = "0.0.3"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
repository = "https://github.com/reem/rust-membuf.git"
description = "A safe-ish wrapper for allocating and reallocating heap buffers."
readme = "README.md"
license = "MIT"

